package util.DdCommunication;

public enum MessageType {
  VALIDATE_USER,
  VALID_USER,
  USERNAME_NOT_FOUND,
  INVALID_PASSWORD,
  REGISTER_USER,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_USERNAMETAKEN
}
