package util.DbCommunication;

public enum MessageType {
  VALIDATE_USER,
  VALID_USER,
  USERNAME_NOT_FOUND,
  INVALID_PASSWORD,
  REGISTER_USER,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_USERNAMETAKEN,
  SAVEGAME,
  SAVEGAME_RESPONSE,
  IS_GAME_SAVED,
  IS_GAME_SAVED_RESPONSE,
  DELETE_GAME_SAVE,
  LOAD_GAME_CONFIG,
  LOAD_GAME_CONFIG_RESULT
}
